export const timezones = [
  'América/Adak',
  'América/Anchorage',
  'América/Anguila',
  'América/Antigua',
  'América/Araguaina',
  'América/Argentina/Buenos Aires',
  'América/Argentina/Catamarca',
  'América/Argentina/Comodoro Rivadavia',
  'América/Argentina/Córdoba',
  'América/Argentina/Jujuy',
  'América/Argentina/La Rioja',
  'América/Argentina/Mendoza',
  'América/Argentina/Río Gallegos',
  'América/Argentina/Salta',
  'América/Argentina/San Juan',
  'América/Argentina/San Luis',
  'América/Argentina/Tucumán',
  'América/Argentina/Ushuaia',
  'América/Aruba',
  'América/Asunción',
  'América/Atikokan',
  'América/Bahía',
  'América/Bahía Banderas',
  'América/Barbados',
  'América/Belem',
  'América/Belice',
  'América/Blanc-Sablon',
  'América/Boa Vista',
  'América/Bogotá',
  'América/Boise',
  'América/Cambridge Bay',
  'América/Campo Grande',
  'América/Cancún',
  'América/Caracas',
  'América/Cayena',
  'América/Caimán',
  'América/Chicago',
  'América/Chihuahua',
  'América/Costa Rica',
  'América/Creston',
  'América/Cuiabá',
  'América/Curazao',
  'América/Danmarkshavn',
  'América/Dawson',
  'América/Dawson Creek',
  'América/Denver',
  'América/Detroit',
  'América/Dominica',
  'América/Edmonton',
  'América/Eirunepe',
  'América/El Salvador',
  'América/Fort Nelson',
  'América/Fortaleza',
  'América/Glace Bay',
  'América/Godthab',
  'América/Goose Bay',
  'América/Grand Turk',
  'América/Grenada',
  'América/Guadalupe',
  'América/Guatemala',
  'América/Guayaquil',
  'América/Guyana',
  'América/Halifax',
  'América/La Habana',
  'América/Hermosillo',
  'América/Indiana/Indianápolis',
  'América/Indiana/Knox',
  'América/Indiana/Marengo',
  'América/Indiana/Petersburg',
  'América/Indiana/Tell City',
  'América/Indiana/Vevay',
  'América/Indiana/Vincennes',
  'América/Indiana/Winamac',
  'América/Inuvik',
  'América/Iqaluit',
  'América/Jamaica',
  'América/Juneau',
  'América/Kentucky/Louisville',
  'América/Kentucky/Monticello',
  'América/La Paz',
  'América/Lima',
  'América/Los Ángeles',
  'América/Lower Princes',
  'América/Maceió',
  'América/Managua',
  'América/Manaos',
  'América/Marigot',
  'América/Martinica',
  'América/Matamoros',
  'América/Mazatlán',
  'América/Menominee',
  'América/Mérida',
  'América/Metlakatla',
  'América/Ciudad de México',
  'América/Miquelon',
  'América/Moncton',
  'América/Monterrey',
  'América/Montevideo',
  'América/Montserrat',
  'América/Nassau',
  'América/Nueva York',
  'América/Nipigon',
  'América/Nome',
  'América/Noronha',
  'América/North Dakota/Beulah',
  'América/North Dakota/Center',
  'América/North Dakota/New Salem',
  'América/Nuuk',
  'América/Ojinaga',
  'América/Panamá',
  'América/Pangnirtung',
  'América/Paramaribo',
  'América/Fénix',
  'América/Port-au-Prince',
  'América/Puerto España',
  'América/Porto Velho',
  'América/Puerto Rico',
  'América/Punta Arenas',
  'América/Rainy River',
  'América/Rankin Inlet',
  'América/Recife',
  'América/Regina',
  'América/Resolute',
  'América/Río Branco',
  'América/Santarem',
  'América/Santiago',
  'América/Santo Domingo',
  'América/São Paulo',
  'América/Scoresbysund',
  'América/Sitka',
  'América/St Barthelemy',
  'América/St Johns',
  'América/St Kitts',
  'América/St Lucia',
  'América/St Thomas',
  'América/St Vincent',
  'América/Swift Current',
  'América/Tegucigalpa',
  'América/Thule',
  'América/Thunder Bay',
  'América/Tijuana',
  'América/Toronto',
  'América/Tortola',
  'América/Vancouver',
  'América/Whitehorse',
  'América/Winnipeg',
  'América/Yakutat',
  'América/Yellowknife'
];
