export const timezones = [
  { value: 'America/Adak', label: '(GMT-10) Adak' },
  { value: 'America/Anchorage', label: '(GMT-9) Anchorage' },
  { value: 'America/Anguilla', label: '(GMT-4) Anguilla' },
  { value: 'America/Antigua', label: '(GMT-4) Antigua' },
  { value: 'America/Araguaina', label: '(GMT-3) Araguaina' },
  { value: 'America/Argentina/Buenos_Aires', label: '(GMT-3) Buenos Aires' },
  { value: 'America/Argentina/Catamarca', label: '(GMT-3) Catamarca' },
  { value: 'America/Argentina/Comodoro_Rivadavia', label: '(GMT-3) Comodoro Rivadavia' },
  { value: 'America/Argentina/Cordoba', label: '(GMT-3) Córdoba' },
  { value: 'America/Argentina/Jujuy', label: '(GMT-3) Jujuy' },
  { value: 'America/Argentina/La_Rioja', label: '(GMT-3) La Rioja' },
  { value: 'America/Argentina/Mendoza', label: '(GMT-3) Mendoza' },
  { value: 'America/Argentina/Rio_Gallegos', label: '(GMT-3) Río Gallegos' },
  { value: 'America/Argentina/Salta', label: '(GMT-3) Salta' },
  { value: 'America/Argentina/San_Juan', label: '(GMT-3) San Juan' },
  { value: 'America/Argentina/San_Luis', label: '(GMT-3) San Luis' },
  { value: 'America/Argentina/Tucuman', label: '(GMT-3) Tucumán' },
  { value: 'America/Argentina/Ushuaia', label: '(GMT-3) Ushuaia' },
  { value: 'America/Aruba', label: '(GMT-4) Aruba' },
  { value: 'America/Asuncion', label: '(GMT-4) Asunción' },
  { value: 'America/Atikokan', label: '(GMT-5) Atikokan' },
  { value: 'America/Bahia', label: '(GMT-3) Bahía' },
  { value: 'America/Bahia_Banderas', label: '(GMT-6) Bahía de Banderas' },
  { value: 'America/Barbados', label: '(GMT-4) Barbados' },
  { value: 'America/Belem', label: '(GMT-3) Belém' },
  { value: 'America/Belize', label: '(GMT-6) Belice' },
  { value: 'America/Blanc-Sablon', label: '(GMT-4) Blanc-Sablon' },
  { value: 'America/Boa_Vista', label: '(GMT-4) Boa Vista' },
  { value: 'America/Bogota', label: '(GMT-5) Bogotá' },
  { value: 'America/Boise', label: '(GMT-7) Boise' },
  { value: 'America/Cambridge_Bay', label: '(GMT-7) Cambridge Bay' },
  { value: 'America/Campo_Grande', label: '(GMT-4) Campo Grande' },
  { value: 'America/Cancun', label: '(GMT-5) Cancún' },
  { value: 'America/Caracas', label: '(GMT-4) Caracas' },
  { value: 'America/Cayenne', label: '(GMT-3) Cayena' },
  { value: 'America/Cayman', label: '(GMT-5) Islas Caimán' },
  { value: 'America/Chicago', label: '(GMT-6) Chicago' },
  { value: 'America/Chihuahua', label: '(GMT-6) Chihuahua' },
  { value: 'America/Costa_Rica', label: '(GMT-6) Costa Rica' },
  { value: 'America/Creston', label: '(GMT-7) Creston' },
  { value: 'America/Cuiaba', label: '(GMT-4) Cuiabá' },
  { value: 'America/Curacao', label: '(GMT-4) Curazao' },
  { value: 'America/Danmarkshavn', label: '(GMT+0) Danmarkshavn' },
  { value: 'America/Dawson', label: '(GMT-7) Dawson' },
  { value: 'America/Dawson_Creek', label: '(GMT-7) Dawson Creek' },
  { value: 'America/Denver', label: '(GMT-7) Denver' },
  { value: 'America/Detroit', label: '(GMT-5) Detroit' },
  { value: 'America/Dominica', label: '(GMT-4) Dominica' },
  { value: 'America/Edmonton', label: '(GMT-7) Edmonton' },
  { value: 'America/Eirunepe', label: '(GMT-5) Eirunepé' },
  { value: 'America/El_Salvador', label: '(GMT-6) El Salvador' },
  { value: 'America/Fort_Nelson', label: '(GMT-7) Fort Nelson' },
  { value: 'America/Fortaleza', label: '(GMT-3) Fortaleza' },
  { value: 'America/Glace_Bay', label: '(GMT-4) Glace Bay' },
  { value: 'America/Godthab', label: '(GMT-3) Nuuk' },
  { value: 'America/Goose_Bay', label: '(GMT-4) Goose Bay' },
  { value: 'America/Grand_Turk', label: '(GMT-5) Grand Turk' },
  { value: 'America/Grenada', label: '(GMT-4) Granada' },
  { value: 'America/Guadeloupe', label: '(GMT-4) Guadalupe' },
  { value: 'America/Guatemala', label: '(GMT-6) Guatemala' },
  { value: 'America/Guayaquil', label: '(GMT-5) Guayaquil' },
  { value: 'America/Guyana', label: '(GMT-4) Guyana' },
  { value: 'America/Halifax', label: '(GMT-4) Halifax' },
  { value: 'America/Havana', label: '(GMT-5) La Habana' },
  { value: 'America/Hermosillo', label: '(GMT-7) Hermosillo' },
  { value: 'America/Indiana/Indianapolis', label: '(GMT-5) Indianápolis' },
  { value: 'America/Indiana/Knox', label: '(GMT-6) Knox, Indiana' },
  { value: 'America/Indiana/Marengo', label: '(GMT-5) Marengo, Indiana' },
  { value: 'America/Indiana/Petersburg', label: '(GMT-5) Petersburg, Indiana' },
  { value: 'America/Indiana/Tell_City', label: '(GMT-6) Tell City, Indiana' },
  { value: 'America/Indiana/Vevay', label: '(GMT-5) Vevay, Indiana' },
  { value: 'America/Indiana/Vincennes', label: '(GMT-5) Vincennes, Indiana' },
  { value: 'America/Indiana/Winamac', label: '(GMT-5) Winamac, Indiana' },
  { value: 'America/Inuvik', label: '(GMT-7) Inuvik' },
  { value: 'America/Iqaluit', label: '(GMT-5) Iqaluit' },
  { value: 'America/Jamaica', label: '(GMT-5) Jamaica' },
  { value: 'America/Juneau', label: '(GMT-9) Juneau' },
  { value: 'America/Kentucky/Louisville', label: '(GMT-5) Louisville' },
  { value: 'America/Kentucky/Monticello', label: '(GMT-5) Monticello' },
  { value: 'America/La_Paz', label: '(GMT-4) La Paz' },
  { value: 'America/Lima', label: '(GMT-5) Lima' },
  { value: 'America/Los_Angeles', label: '(GMT-8) Los Ángeles' },
  { value: 'America/Lower_Princes', label: '(GMT-4) Lower Prince’s Quarter' },
  { value: 'America/Maceio', label: '(GMT-3) Maceió' },
  { value: 'America/Managua', label: '(GMT-6) Managua' },
  { value: 'America/Manaus', label: '(GMT-4) Manaos' },
  { value: 'America/Marigot', label: '(GMT-4) Marigot' },
  { value: 'America/Martinique', label: '(GMT-4) Martinica' },
  { value: 'America/Matamoros', label: '(GMT-6) Matamoros' },
  { value: 'America/Mazatlan', label: '(GMT-7) Mazatlán' },
  { value: 'America/Menominee', label: '(GMT-6) Menominee' },
  { value: 'America/Merida', label: '(GMT-6) Mérida' },
  { value: 'America/Metlakatla', label: '(GMT-9) Metlakatla' },
  { value: 'America/Mexico_City', label: '(GMT-6) Ciudad de México' },
  { value: 'America/Miquelon', label: '(GMT-3) Miquelon' },
  { value: 'America/Moncton', label: '(GMT-4) Moncton' },
  { value: 'America/Monterrey', label: '(GMT-6) Monterrey' },
  { value: 'America/Montevideo', label: '(GMT-3) Montevideo' },
  { value: 'America/Montserrat', label: '(GMT-4) Montserrat' },
  { value: 'America/Nassau', label: '(GMT-5) Nassau' },
  { value: 'America/New_York', label: '(GMT-5) Nueva York' },
  { value: 'America/Nipigon', label: '(GMT-5) Nipigon' },
  { value: 'America/Nome', label: '(GMT-9) Nome' },
  { value: 'America/Noronha', label: '(GMT-2) Fernando de Noronha' },
  { value: 'America/North_Dakota/Beulah', label: '(GMT-6) Beulah, ND' },
  { value: 'America/North_Dakota/Center', label: '(GMT-6) Center, ND' },
  { value: 'America/North_Dakota/New_Salem', label: '(GMT-6) New Salem, ND' },
  { value: 'America/Nuuk', label: '(GMT-3) Nuuk' },
  { value: 'America/Ojinaga', label: '(GMT-7) Ojinaga' },
  { value: 'America/Panama', label: '(GMT-5) Panamá' },
  { value: 'America/Pangnirtung', label: '(GMT-5) Pangnirtung' },
  { value: 'America/Paramaribo', label: '(GMT-3) Paramaribo' },
  { value: 'America/Phoenix', label: '(GMT-7) Fénix' },
  { value: 'America/Port-au-Prince', label: '(GMT-5) Puerto Príncipe' },
  { value: 'America/Port_of_Spain', label: '(GMT-4) Puerto España' },
  { value: 'America/Porto_Velho', label: '(GMT-4) Porto Velho' },
  { value: 'America/Puerto_Rico', label: '(GMT-4) Puerto Rico' },
  { value: 'America/Punta_Arenas', label: '(GMT-3) Punta Arenas' },
  { value: 'America/Rainy_River', label: '(GMT-6) Rainy River' },
  { value: 'America/Rankin_Inlet', label: '(GMT-6) Rankin Inlet' },
  { value: 'America/Recife', label: '(GMT-3) Recife' },
  { value: 'America/Regina', label: '(GMT-6) Regina' },
  { value: 'America/Resolute', label: '(GMT-6) Resolute' },
  { value: 'America/Rio_Branco', label: '(GMT-5) Río Branco' },
  { value: 'America/Santarem', label: '(GMT-3) Santarém' },
  { value: 'America/Santiago', label: '(GMT-4) Santiago' },
  { value: 'America/Santo_Domingo', label: '(GMT-4) Santo Domingo' },
  { value: 'America/Sao_Paulo', label: '(GMT-3) São Paulo' },
  { value: 'America/Scoresbysund', label: '(GMT-1) Ittoqqortoormiit' },
  { value: 'America/Sitka', label: '(GMT-9) Sitka' },
  { value: 'America/St_Barthelemy', label: '(GMT-4) St. Barthelemy' },
  { value: 'America/St_Johns', label: '(GMT-3:30) St. John’s' },
  { value: 'America/St_Kitts', label: '(GMT-4) St. Kitts' },
  { value: 'America/St_Lucia', label: '(GMT-4) St. Lucia' },
  { value: 'America/St_Thomas', label: '(GMT-4) St. Thomas' },
  { value: 'America/St_Vincent', label: '(GMT-4) St. Vincent' },
  { value: 'America/Swift_Current', label: '(GMT-6) Swift Current' },
  { value: 'America/Tegucigalpa', label: '(GMT-6) Tegucigalpa' },
  { value: 'America/Thule', label: '(GMT-4) Thule' },
  { value: 'America/Thunder_Bay', label: '(GMT-5) Thunder Bay' },
  { value: 'America/Tijuana', label: '(GMT-8) Tijuana' },
  { value: 'America/Toronto', label: '(GMT-5) Toronto' },
  { value: 'America/Tortola', label: '(GMT-4) Tórtola' },
  { value: 'America/Vancouver', label: '(GMT-8) Vancouver' },
  { value: 'America/Whitehorse', label: '(GMT-7) Whitehorse' },
  { value: 'America/Winnipeg', label: '(GMT-6) Winnipeg' },
  { value: 'America/Yakutat', label: '(GMT-9) Yakutat' },
  { value: 'America/Yellowknife', label: '(GMT-7) Yellowknife' }
];
